import LegalPage, { H2, P, UL, LI } from "./LegalPage";

export default function Terms() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="May 26, 2026">
      <P>
        These Terms govern your use of TripJam ("we", "us", "the service"). By
        creating an account or using TripJam, you agree to these terms. If you
        don't agree, please don't use the service.
      </P>

      <H2>1. The service</H2>
      <P>
        TripJam helps you plan trips using AI. It generates suggested itineraries,
        route options, destination guides, and lets you save, edit, share, and
        export them. The AI may make mistakes — always double-check critical
        details (opening hours, visas, transit, hotel availability) before relying
        on them.
      </P>

      <H2>2. Your account</H2>
      <UL>
        <LI>
          You must be 13 or older. By signing up you confirm this.
        </LI>
        <LI>
          One account per person. Don't create multiple accounts to abuse the free
          credit grant.
        </LI>
        <LI>
          You're responsible for keeping your password safe. Don't share your
          credentials.
        </LI>
        <LI>
          You can sign up with email + password or "Sign in with Google" (when
          available). If you use both with the same email, they get linked.
        </LI>
      </UL>

      <H2>3. Acceptable use</H2>
      <P>You agree not to:</P>
      <UL>
        <LI>
          Scrape, mirror, or automate TripJam beyond normal individual use.
        </LI>
        <LI>
          Reverse-engineer, decompile, or attempt to extract our prompts or
          source data.
        </LI>
        <LI>
          Use the AI to generate illegal, harmful, hateful, or sexually explicit
          content.
        </LI>
        <LI>
          Resell credits, accounts, or AI-generated content as a standalone product.
        </LI>
        <LI>
          Use TripJam to impersonate others or for fraud.
        </LI>
        <LI>
          Probe, scan, or test the vulnerability of our systems without written
          permission.
        </LI>
      </UL>
      <P>
        Violations may result in account suspension or deletion, with no refund.
      </P>

      <H2>4. Credits + payments</H2>
      <UL>
        <LI>
          New accounts get a free starting credit balance. Credits do not have a
          cash value and are not refundable except as described in section 5.
        </LI>
        <LI>
          Credits are consumed when you use AI features (generating routes,
          itineraries, magazines, chat). The exact cost per call is displayed in
          your account.
        </LI>
        <LI>
          You can purchase additional credits via Lemon Squeezy, our payment
          processor. They handle billing, tax, and refunds on our behalf.
        </LI>
        <LI>
          Credits do not expire. They remain in your account until used or until
          your account is deleted.
        </LI>
        <LI>
          Prices and pack sizes may change. Changes apply to future purchases only.
        </LI>
      </UL>

      <H2>5. Refunds</H2>
      <P>
        We offer a 30-day no-questions-asked refund window from your purchase date
        if you're unhappy with the service, with the following exceptions:
      </P>
      <UL>
        <LI>
          If you've used more than 50% of the credits in the pack, we'll prorate
          the refund.
        </LI>
        <LI>
          Refunds for abuse-based suspensions are not available.
        </LI>
      </UL>
      <P>
        To request a refund, email{" "}
        <a href="mailto:achinj.work@gmail.com" style={{ color: "#2563A8" }}>
          achinj.work@gmail.com
        </a>{" "}
        with your order ID. Refunds typically process within 5-10 business days
        via Lemon Squeezy.
      </P>

      <H2>6. Your content</H2>
      <P>
        You own the trips, notes, comments, and content you create in TripJam. You
        grant us a limited license to store, display, and process this content as
        needed to operate the service (e.g., generating AI responses based on
        your trip details). We don't claim ownership of your content and don't
        use it to train AI models.
      </P>

      <H2>7. AI-generated content</H2>
      <P>
        Itineraries, magazines, and chat responses are generated by third-party AI
        (Anthropic Claude). Output may be inaccurate, outdated, or unsuitable —
        especially for time-sensitive details like opening hours, visa rules,
        weather, or pricing. <strong>Always verify critical information from
        authoritative sources.</strong> We are not liable for decisions you make
        based on AI output.
      </P>

      <H2>8. Sharing trips</H2>
      <P>
        Trips are private by default. When you generate a share link, the trip
        becomes viewable by anyone with the link until you revoke it. You're
        responsible for what you share.
      </P>

      <H2>9. Account termination</H2>
      <P>
        You may delete your account anytime by emailing us. We may suspend or
        terminate accounts that violate these Terms or where required by law. On
        termination, your trip data is permanently deleted within 30 days (see
        Privacy Policy for details).
      </P>

      <H2>10. Disclaimers</H2>
      <P>
        TripJam is provided "as is" without warranty of any kind. We don't
        guarantee uninterrupted access, error-free operation, or that the AI will
        meet your expectations. We are not a travel agent and don't make bookings
        on your behalf.
      </P>

      <H2>11. Limitation of liability</H2>
      <P>
        To the maximum extent permitted by law, our total liability for any claim
        arising from your use of TripJam is limited to the amount you paid us in
        the 12 months prior to the claim, or $50 USD, whichever is greater. We are
        not liable for indirect, incidental, or consequential damages (lost
        trips, missed bookings, etc.).
      </P>

      <H2>12. Changes to these Terms</H2>
      <P>
        We may update these Terms. The "Last updated" date at the top changes
        when we do. For material changes affecting your rights or payments, we'll
        notify active users by email. Continued use after changes means you
        accept the new Terms.
      </P>

      <H2>13. Governing law</H2>
      <P>
        These Terms are governed by the laws of India. Disputes will be resolved
        in the courts of Bangalore, Karnataka, India.
      </P>

      <H2>14. Contact</H2>
      <P>
        Questions about these Terms? Email{" "}
        <a href="mailto:achinj.work@gmail.com" style={{ color: "#2563A8" }}>
          achinj.work@gmail.com
        </a>
        .
      </P>
    </LegalPage>
  );
}
