// Inbound booking-email ingestion (TripIt-style):
//   forward a hotel confirmation → Resend inbound → this webhook → Haiku
//   parse → the matching trip's hotels_data gains {status:"booked",
//   confirmation, via:"email"} → the itinerary shows ✓ Booked → the sender
//   gets an outcome receipt in their inbox.
//
// Deploy with --no-verify-jwt (Resend calls it); webhook authenticity via
// Svix signatures. EMAIL SENDER authenticity via Resend's structured
// authentication verdict (SPF/DKIM/DMARC) fetched with the full content —
// spoofed From headers fail DKIM+SPF and are dropped (fail-closed: no
// verdict → no processing).
//
// Safety model (hardened after independent review, 2026-09-24):
//   - Svix-verified events only; email.received only
//   - sender must pass SPF or DKIM, must not fail DMARC, must match a
//     profiles.email; auto-generated mail (Auto-Submitted/Precedence) drops
//   - claim-first dedupe on message_id (partial unique index) — retries
//     can never double-process; no message id → dropped
//   - per-sender cap: 20 inbound emails/day (the claim rows are the meter)
//   - deterministic routing: plus-address (member-aware) → booking dates →
//     soonest trip; an explicit plus-address that matches nothing STOPS
//     with a receipt, never falls through
//   - cancellations unbook, never book; receipts escape all email-derived
//     values; receipts are capped, threaded, Auto-Submitted, best-effort

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, svix-id, svix-timestamp, svix-signature",
};

const enc = new TextEncoder();

// HTML-escape every email-derived value before it enters receipt markup —
// a "hotel" named <a href=evil> must render as text, not phishing.
function esc(s: unknown): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function stripCrlf(s: string): string {
  return s.replace(/[\r\n]+/g, " ").trim();
}

async function verifySvix(req: Request, payload: string): Promise<boolean> {
  const secret = Deno.env.get("RESEND_INBOUND_WEBHOOK_SECRET") || "";
  if (!secret) return false;
  const id = req.headers.get("svix-id");
  const ts = req.headers.get("svix-timestamp");
  const sigs = req.headers.get("svix-signature");
  if (!id || !ts || !sigs) return false;
  if (Math.abs(Date.now() / 1000 - Number(ts)) > 300) return false;
  const secretBytes = Uint8Array.from(
    atob(secret.startsWith("whsec_") ? secret.slice(6) : secret),
    (c) => c.charCodeAt(0),
  );
  const key = await crypto.subtle.importKey(
    "raw",
    secretBytes,
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const mac = await crypto.subtle.sign(
    "HMAC",
    key,
    enc.encode(`${id}.${ts}.${payload}`),
  );
  const expected = btoa(String.fromCharCode(...new Uint8Array(mac)));
  return sigs
    .split(" ")
    .some((s) => s.split(",")[1] === expected || s === `v1,${expected}`);
}

function extractAddress(from: string): string {
  const m = from.match(/<([^>]+)>/);
  return (m ? m[1] : from).trim().toLowerCase();
}

type FullEmail = {
  text: string;
  html: string;
  subject: string;
  spf: string;
  dkim: string;
  dmarc: string;
  autoGenerated: boolean;
};

async function fetchReceivedEmail(
  emailId: string,
  apiKey: string,
): Promise<FullEmail | null> {
  try {
    const res = await fetch(
      `https://api.resend.com/emails/receiving/${emailId}`,
      { headers: { Authorization: `Bearer ${apiKey}` } },
    );
    if (!res.ok) return null;
    const d = await res.json();
    const auth = d.authentication || {};
    const headerList: Array<{ name?: string; value?: string }> = Array.isArray(
      d.headers,
    )
      ? d.headers
      : [];
    const header = (n: string) =>
      String(
        headerList.find((h) => (h.name || "").toLowerCase() === n)?.value || "",
      ).toLowerCase();
    const autoGenerated =
      (header("auto-submitted") !== "" && header("auto-submitted") !== "no") ||
      /bulk|auto_reply|junk/.test(header("precedence")) ||
      header("x-auto-response-suppress").length > 0;
    return {
      text: d.text || "",
      html: d.html || "",
      subject: d.subject || "",
      spf: String(auth.spf || "none"),
      dkim: String(auth.dkim || "none"),
      dmarc: String(auth.dmarc || "none"),
      autoGenerated,
    };
  } catch {
    return null;
  }
}

function stripHtml(html: string): string {
  return html
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

async function parseBooking(
  anthropicKey: string,
  subject: string,
  bodyText: string,
): Promise<{ parsed: any; usage: any } | null> {
  const aiRes = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "x-api-key": anthropicKey,
      "anthropic-version": "2023-06-01",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 400,
      messages: [
        {
          role: "user",
          content: `This is a forwarded travel confirmation email. Extract booking facts as MINIFIED JSON only (no prose):
{"kind":"hotel"|"flight"|"other","status":"confirmed"|"cancelled","hotel":{"name":"","city":"","confirmation":"","checkin":"YYYY-MM-DD or empty","checkout":"YYYY-MM-DD or empty"},"flight":{"carrier":"","number":"","date":"","from":"","to":"","confirmation":""},"summary":"one line describing the booking"}
Only include facts explicitly present. Empty strings for anything absent. kind="other" if it is not clearly a hotel or flight booking. status="cancelled" when the email announces a cancellation (even of a previously confirmed booking) — NEVER "confirmed" for cancellation/refund notices.

SUBJECT: ${subject}
BODY:
${bodyText || "(body unavailable — use the subject line only)"}`,
        },
      ],
    }),
  });
  if (!aiRes.ok) return null;
  const ai = await aiRes.json();
  const rawOut = ai?.content?.[0]?.text || "{}";
  let parsed: any = {};
  try {
    parsed = JSON.parse(
      rawOut.slice(rawOut.indexOf("{"), rawOut.lastIndexOf("}") + 1),
    );
  } catch {
    parsed = { kind: "other", summary: subject };
  }
  return { parsed, usage: ai?.usage || {} };
}

// Member-aware candidates: trips the user created OR is a member of, not
// yet ended — so co-travellers' forwards can route to shared trips.
async function fetchCandidates(
  supabaseUrl: string,
  db: Record<string, string>,
  userId: string,
): Promise<any[]> {
  const today = new Date().toISOString().slice(0, 10);
  let memberIds: string[] = [];
  try {
    const mRes = await fetch(
      `${supabaseUrl}/rest/v1/trip_members?user_id=eq.${userId}&select=trip_id`,
      { headers: db },
    );
    if (mRes.ok) memberIds = (await mRes.json()).map((r: any) => r.trip_id);
  } catch {
    /* member lookup best-effort */
  }
  const orParts = [`created_by.eq.${userId}`];
  if (memberIds.length)
    orParts.push(`id.in.(${memberIds.slice(0, 50).join(",")})`);
  const tRes = await fetch(
    `${supabaseUrl}/rest/v1/trips?or=(${orParts.join(",")})&end_date=gte.${today}&select=id,name,hotels_data,destination,start_date,end_date&order=start_date.asc&limit=100`,
    { headers: db },
  );
  return tRes.ok ? await tRes.json() : [];
}

// plus_miss: an explicit trip address that matches nothing must STOP the
// pipeline (receipt + no writes), never fall through to a guess.
function routeTrip(
  candidates: any[],
  parsed: any,
  toAddrs: string[],
): { trip: any; routedBy: string } {
  const plusMatch = toAddrs
    .map((a) => a.match(/\+([a-f0-9-]{4,36})@/))
    .find(Boolean);
  if (plusMatch) {
    const code = plusMatch[1];
    const trip = candidates.find((t) => String(t.id).startsWith(code)) || null;
    return trip
      ? { trip, routedBy: "trip_address" }
      : { trip: null, routedBy: "plus_miss" };
  }
  if (parsed.kind === "hotel" && parsed.hotel?.checkin) {
    const ci = parsed.hotel.checkin;
    const trip =
      candidates.find((t) => ci >= t.start_date && ci <= t.end_date) || null;
    if (trip) return { trip, routedBy: "checkin_date" };
  }
  if (parsed.kind === "flight" && parsed.flight?.date) {
    const fd = parsed.flight.date;
    const trip =
      candidates.find((t) => fd >= t.start_date && fd <= t.end_date) || null;
    if (trip) return { trip, routedBy: "flight_date" };
  }
  return { trip: candidates[0] || null, routedBy: "fallback" };
}

/* P0 — reply-back receipt. Callers must esc() every email-derived value in
 * heading/line. Loop-safety: Auto-Submitted, threaded, verified senders
 * only, 20/day cap (log insert AWAITED so the counter is reliable). */
async function sendReceipt(opts: {
  supabaseUrl: string;
  db: Record<string, string>;
  to: string;
  origSubject: string;
  origMessageId: string;
  heading: string;
  line: string;
  tripId?: string;
  senderProfileId?: string;
}): Promise<void> {
  try {
    const key = Deno.env.get("RESEND_API_KEY");
    const from = Deno.env.get("EMAIL_FROM") || "TripJam <trips@tripjam.co>";
    if (!key) return;
    const dayAgo = new Date(Date.now() - 24 * 3600 * 1000).toISOString();
    const capRes = await fetch(
      `${opts.supabaseUrl}/rest/v1/email_log?type=eq.receipt&recipient=eq.${encodeURIComponent(opts.to)}&created_at=gte.${dayAgo}&select=id`,
      { headers: opts.db },
    );
    if (capRes.ok && (await capRes.json()).length >= 20) return;
    const tripUrl = opts.tripId
      ? `https://tripjam.co/trip/${opts.tripId}`
      : "https://tripjam.co";
    const html = `
  <div style="max-width:480px;margin:0 auto;background:#fff;border:1px solid #E2DDD5;border-radius:16px;padding:28px;font-family:Georgia,serif">
    <div style="font-size:14px;letter-spacing:.08em;color:#587284;margin-bottom:14px">TRIPJAM</div>
    <div style="font-size:20px;margin-bottom:10px">${opts.heading}</div>
    <div style="font-size:14px;line-height:1.6;color:#3a4a58;margin-bottom:22px">${opts.line}</div>
    <a href="${tripUrl}" style="display:inline-block;background:#2563A8;color:#fff;text-decoration:none;border-radius:10px;padding:11px 22px;font-size:14px">Open the trip</a>
  </div>`;
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${key}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from,
        to: [opts.to],
        subject:
          `Re: ${stripCrlf(opts.origSubject) || "your forwarded booking"}`.slice(
            0,
            160,
          ),
        html,
        headers: {
          "Auto-Submitted": "auto-replied",
          ...(opts.origMessageId
            ? {
                "In-Reply-To": opts.origMessageId,
                References: opts.origMessageId,
              }
            : {}),
        },
      }),
    });
    if (res.ok)
      // Awaited: this row IS the rate-limit counter — a dropped write
      // would make the cap soft.
      await fetch(`${opts.supabaseUrl}/rest/v1/email_log`, {
        method: "POST",
        headers: opts.db,
        body: JSON.stringify({
          type: "receipt",
          recipient: opts.to,
          sender_id: opts.senderProfileId || null,
          trip_id: opts.tripId || null,
        }),
      });
  } catch {
    /* receipts are best-effort */
  }
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS")
    return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST")
    return new Response("method not allowed", {
      status: 405,
      headers: corsHeaders,
    });

  const payload = await req.text();

  // Dry-run mode: authenticated parse+route diagnostics, no trip writes.
  // Metered: llm_usage row + 30 runs/user/day.
  try {
    const maybe = JSON.parse(payload);
    if (maybe?.dry_run === true) {
      const auth = req.headers.get("authorization") || "";
      const userRes = await fetch(
        `${Deno.env.get("SUPABASE_URL")}/auth/v1/user`,
        {
          headers: {
            Authorization: auth,
            apikey: Deno.env.get("SUPABASE_ANON_KEY") || "",
          },
        },
      );
      if (!userRes.ok)
        return new Response(JSON.stringify({ error: "unauthorized" }), {
          status: 401,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      const user = await userRes.json();
      const sk = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
      const sUrl = Deno.env.get("SUPABASE_URL")!;
      const dbh = {
        apikey: sk,
        Authorization: `Bearer ${sk}`,
        "Content-Type": "application/json",
      };
      const dayAgo = new Date(Date.now() - 24 * 3600 * 1000).toISOString();
      const capRes = await fetch(
        `${sUrl}/rest/v1/llm_usage?function_name=eq.inbound-email:dry&user_id=eq.${user.id}&created_at=gte.${dayAgo}&select=id`,
        { headers: dbh },
      ).catch(() => null);
      if (capRes?.ok && (await capRes.json()).length >= 30)
        return new Response(JSON.stringify({ error: "daily dry-run cap" }), {
          status: 429,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      const cands = await fetchCandidates(sUrl, dbh, user.id);
      const pr = await parseBooking(
        Deno.env.get("ANTHROPIC_API_KEY")!,
        String(maybe.subject || ""),
        String(maybe.body || "").slice(0, 8000),
      );
      if (!pr)
        return new Response(JSON.stringify({ error: "parse failed" }), {
          status: 502,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      fetch(`${sUrl}/rest/v1/llm_usage`, {
        method: "POST",
        headers: dbh,
        body: JSON.stringify({
          function_name: "inbound-email:dry",
          model: "claude-haiku-4-5-20251001",
          user_id: user.id,
          input_tokens: pr.usage?.input_tokens || 0,
          output_tokens: pr.usage?.output_tokens || 0,
        }),
      }).catch(() => {});
      const routed = cands.length
        ? routeTrip(
            cands,
            pr.parsed,
            (maybe.to ? [String(maybe.to)] : []).map((s) => s.toLowerCase()),
          )
        : { trip: null, routedBy: "no_active_trip" };
      return Response.json(
        {
          dry_run: true,
          parsed: pr.parsed,
          routedBy: routed.routedBy,
          trip: routed.trip?.name || null,
          candidates: cands.map((c) => c.name),
        },
        { headers: corsHeaders },
      );
    }
  } catch {
    /* not JSON or not dry_run — fall through to webhook path */
  }

  if (!(await verifySvix(req, payload)))
    return new Response(JSON.stringify({ error: "invalid signature" }), {
      status: 401,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  let event: any;
  try {
    event = JSON.parse(payload);
  } catch {
    return new Response("bad payload", { status: 400, headers: corsHeaders });
  }
  if (event.type !== "email.received")
    return Response.json({ ignored: event.type }, { headers: corsHeaders });

  const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const anthropicKey = Deno.env.get("ANTHROPIC_API_KEY")!;
  const resendKey =
    Deno.env.get("RESEND_INBOUND_API_KEY") || Deno.env.get("RESEND_API_KEY")!;
  const db = {
    apikey: serviceKey,
    Authorization: `Bearer ${serviceKey}`,
    "Content-Type": "application/json",
  };

  const data = event.data || {};
  const sender = extractAddress(String(data.from || ""));
  const messageId = String(data.message_id || data.email_id || "");
  const subject = String(data.subject || "");

  // No message identity → no dedupe possible → drop (a constant key would
  // make the first such email swallow all later ones).
  if (!messageId)
    return Response.json(
      { dropped: "no message id" },
      { headers: corsHeaders },
    );

  // ── Claim-first dedupe: INSERT the marker BEFORE processing. The partial
  // unique index on email_log(type) for 'inbound:%' makes retries collide
  // here instead of double-processing (receipts, feed rows, bookings).
  const dedupeKey = `inbound:${messageId}`.slice(0, 250);
  const claim = await fetch(`${supabaseUrl}/rest/v1/email_log`, {
    method: "POST",
    headers: db,
    body: JSON.stringify({ type: dedupeKey, recipient: sender }),
  });
  if (!claim.ok) {
    const errText = await claim.text();
    if (/duplicate|23505|unique/i.test(errText))
      return Response.json({ deduped: true }, { headers: corsHeaders });
    return new Response(JSON.stringify({ error: "claim failed" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  // ── Sender → user (silent drop for unknowns — no probing oracle) ──────
  const profRes = await fetch(
    `${supabaseUrl}/rest/v1/profiles?email=eq.${encodeURIComponent(sender)}&select=id&limit=1`,
    { headers: db },
  );
  const prof = profRes.ok ? (await profRes.json())[0] : null;
  if (!prof)
    return Response.json(
      { dropped: "unknown sender" },
      { headers: corsHeaders },
    );

  // ── Per-sender processing cap (the claim rows are the meter) ─────────
  const dayAgo = new Date(Date.now() - 24 * 3600 * 1000).toISOString();
  const meterRes = await fetch(
    `${supabaseUrl}/rest/v1/email_log?type=like.inbound:*&recipient=eq.${encodeURIComponent(sender)}&created_at=gte.${dayAgo}&select=id`,
    { headers: db },
  );
  if (meterRes.ok && (await meterRes.json()).length > 20)
    return Response.json({ dropped: "daily cap" }, { headers: corsHeaders });

  // ── Full content + SENDER authenticity (fail-closed) ─────────────────
  const full = await fetchReceivedEmail(String(data.email_id || ""), resendKey);
  if (!full)
    return Response.json(
      { dropped: "content unavailable — cannot verify sender" },
      { headers: corsHeaders },
    );
  if ((full.spf !== "pass" && full.dkim !== "pass") || full.dmarc === "fail")
    return Response.json(
      { dropped: "sender authentication failed" },
      { headers: corsHeaders },
    );
  if (full.autoGenerated)
    return Response.json(
      { dropped: "auto-generated mail" },
      { headers: corsHeaders },
    );
  const bodyText = (full.text || stripHtml(full.html)).slice(0, 8000);

  // ── Candidates (member-aware) ─────────────────────────────────────────
  const candidates = await fetchCandidates(supabaseUrl, db, prof.id);
  if (candidates.length === 0) {
    await sendReceipt({
      supabaseUrl,
      db,
      to: sender,
      origSubject: subject,
      origMessageId: messageId,
      heading: "No upcoming trip to attach this to",
      line: "We received your booking email, but there's no upcoming trip on your account yet. Create the trip first, then forward it again.",
      senderProfileId: prof.id,
    });
    return Response.json(
      { dropped: "no active trip" },
      { headers: corsHeaders },
    );
  }

  // ── Parse ─────────────────────────────────────────────────────────────
  const pr = await parseBooking(anthropicKey, subject, bodyText);
  if (!pr)
    return new Response(JSON.stringify({ error: "parse model failed" }), {
      status: 502,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  const parsed = pr.parsed;

  // ── Route ─────────────────────────────────────────────────────────────
  const toAddrs: string[] = Array.isArray(data.to)
    ? data.to.map((t: any) => String(t).toLowerCase())
    : [String(data.to || "").toLowerCase()];
  const { trip, routedBy } = routeTrip(candidates, parsed, toAddrs);

  if (routedBy === "plus_miss" || !trip) {
    await sendReceipt({
      supabaseUrl,
      db,
      to: sender,
      origSubject: subject,
      origMessageId: messageId,
      heading: "That trip address didn't match",
      line: "The trip this address points to has ended or isn't on your account. Grab the current address from the trip's Travel & Hotels section and forward again.",
      senderProfileId: prof.id,
    });
    return Response.json(
      { dropped: "plus address matched no trip" },
      { headers: corsHeaders },
    );
  }

  // usage log (fire-and-forget)
  fetch(`${supabaseUrl}/rest/v1/llm_usage`, {
    method: "POST",
    headers: db,
    body: JSON.stringify({
      trip_id: trip.id,
      function_name: "inbound-email",
      model: "claude-haiku-4-5-20251001",
      input_tokens: pr.usage?.input_tokens || 0,
      output_tokens: pr.usage?.output_tokens || 0,
    }),
  }).catch(() => {});

  // ── Apply ─────────────────────────────────────────────────────────────
  let applied = "logged";
  if (
    parsed.kind === "hotel" &&
    parsed.hotel?.name &&
    parsed.status === "cancelled"
  ) {
    const list: any[] = Array.isArray(trip.hotels_data)
      ? [...trip.hotels_data]
      : [];
    const idx = list.findIndex(
      (x) =>
        x.name?.toLowerCase() === parsed.hotel.name.toLowerCase() ||
        (parsed.hotel.confirmation &&
          x.confirmation === parsed.hotel.confirmation),
    );
    if (idx >= 0) {
      list[idx] = { ...list[idx], status: null, confirmation: "" };
      const upd = await fetch(`${supabaseUrl}/rest/v1/trips?id=eq.${trip.id}`, {
        method: "PATCH",
        headers: { ...db, Prefer: "return=representation" },
        body: JSON.stringify({ hotels_data: list }),
      });
      applied = upd.ok ? "hotel_unbooked" : "hotel_update_failed";
    } else {
      applied = "cancellation_noted";
    }
  } else if (parsed.kind === "hotel" && parsed.hotel?.name) {
    const h = parsed.hotel;
    const list: any[] = Array.isArray(trip.hotels_data)
      ? [...trip.hotels_data]
      : [];
    // Match by identity (name/confirmation) first; a same-city slot only
    // absorbs the booking when it isn't already a DIFFERENT booked hotel —
    // never silently destroy an existing booking's confirmation.
    let idx = list.findIndex(
      (x) =>
        x.name?.toLowerCase() === h.name.toLowerCase() ||
        (h.confirmation && x.confirmation === h.confirmation),
    );
    if (idx < 0)
      idx = list.findIndex(
        (x) =>
          h.city &&
          x.city?.toLowerCase() === h.city.toLowerCase() &&
          x.status !== "booked",
      );
    const entry = {
      city: idx >= 0 ? list[idx].city : h.city || trip.destination,
      name: h.name,
      status: "booked",
      confirmation: h.confirmation || "",
      via: "email",
    };
    if (idx >= 0) list[idx] = { ...list[idx], ...entry };
    else list.push(entry);
    const upd = await fetch(`${supabaseUrl}/rest/v1/trips?id=eq.${trip.id}`, {
      method: "PATCH",
      headers: { ...db, Prefer: "return=representation" },
      body: JSON.stringify({ hotels_data: list }),
    });
    applied = upd.ok ? "hotel_booked" : "hotel_update_failed";
  }

  // feed row
  await fetch(`${supabaseUrl}/rest/v1/activity_log`, {
    method: "POST",
    headers: db,
    body: JSON.stringify({
      trip_id: trip.id,
      user_id: prof.id,
      action: "email_ingested",
      entity_type: "trip",
      entity_id: trip.id,
      summary:
        (parsed.summary ||
          `forwarded a booking email${parsed.hotel?.name ? ` — ${parsed.hotel.name}` : ""}`) +
        (routedBy !== "fallback" ? "" : " (routed to soonest trip)"),
    }),
  }).catch(() => {});

  // ── P0: outcome receipt (all email-derived values escaped) ────────────
  const receipt = (() => {
    const tripLabel = `<b>${esc(trip.name)}</b>`;
    if (applied === "hotel_booked")
      return {
        heading: `✓ ${esc(parsed.hotel.name)} is booked`,
        line: `Marked as booked on ${tripLabel}${parsed.hotel.confirmation ? ` with confirmation <b>#${esc(parsed.hotel.confirmation)}</b>` : ""}. You'll see it on the itinerary and in Travel &amp; Hotels.`,
      };
    if (applied === "hotel_unbooked")
      return {
        heading: `Cancellation noted — ${esc(parsed.hotel.name)}`,
        line: `That stay is no longer marked booked on ${tripLabel}.`,
      };
    if (applied === "cancellation_noted")
      return {
        heading: "Cancellation received",
        line: `We noted the cancellation on ${tripLabel}'s activity feed — no matching booked stay to update.`,
      };
    if (applied === "hotel_update_failed")
      return {
        heading: "We hit a snag saving that booking",
        line: `We read the booking fine but couldn't save it to ${tripLabel} just now. Forward it once more in a few minutes.`,
      };
    if (
      parsed.kind === "flight" &&
      (parsed.flight?.number || parsed.flight?.confirmation)
    )
      return {
        heading: `✈️ Flight noted on ${esc(trip.name)}`,
        line: `${esc(parsed.flight.carrier || "")} ${esc(parsed.flight.number || "")} is on the trip's activity feed. Flight bookings land in Travel &amp; Hotels soon.`,
      };
    return {
      heading: "We couldn't read that as a booking",
      line: `It's saved on ${tripLabel}'s activity feed, but nothing was booked. Forwarding the original confirmation email (rather than a summary) usually works best.`,
    };
  })();
  await sendReceipt({
    supabaseUrl,
    db,
    to: sender,
    origSubject: subject,
    origMessageId: messageId,
    heading: receipt.heading,
    line: receipt.line,
    tripId: trip.id,
    senderProfileId: prof.id,
  });

  return Response.json(
    { ok: true, applied, kind: parsed.kind, trip: trip.name, routedBy },
    { headers: corsHeaders },
  );
});
