// Inbound booking ingestion (TripIt-style):
//   forward a hotel/flight/train confirmation → Resend inbound → this
//   webhook → Haiku parse → the matching trip's hotels_data gains
//   {status:"booked", confirmation, via:"email"} or travel_data gains a
//   leg {kind, route, date, times, ref} → the itinerary shows it → the
//   sender gets an outcome receipt in their inbox.
//
// P3 additions (2026-09-25): global flight/train legs in trips.travel_data
// (any count, any date — mid-trip legs are first-class), boundary
// auto-fill of arrival/departure on first/last-day legs, and dry_run
// accepts an image/PDF `file` for the in-app upload path.
//
// Deploy with --no-verify-jwt (Resend calls it); webhook authenticity via
// Svix signatures. EMAIL SENDER authenticity via Resend's structured
// authentication verdict (SPF/DKIM/DMARC) fetched with the full content —
// spoofed From headers fail DKIM+SPF and are dropped (fail-closed: no
// verdict → no processing).
//
// Safety model (hardened after independent review, 2026-09-24):
//   - Svix-verified events only; email.received only
//   - sender must pass SPF or DKIM, must not fail DMARC, must match a
//     profiles.email; auto-generated mail (Auto-Submitted/Precedence) drops
//   - claim-first dedupe on message_id (partial unique index) — retries
//     can never double-process; no message id → dropped
//   - per-sender cap: 20 inbound emails/day (the claim rows are the meter)
//   - deterministic routing: plus-address (member-aware) → booking dates →
//     soonest trip; an explicit plus-address that matches nothing STOPS
//     with a receipt, never falls through
//   - cancellations unbook, never book; receipts escape all email-derived
//     values; receipts are capped, threaded, Auto-Submitted, best-effort

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, svix-id, svix-timestamp, svix-signature",
};

const enc = new TextEncoder();

// HTML-escape every email-derived value before it enters receipt markup —
// a "hotel" named <a href=evil> must render as text, not phishing.
function esc(s: unknown): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function stripCrlf(s: string): string {
  return s.replace(/[\r\n]+/g, " ").trim();
}

async function verifySvix(req: Request, payload: string): Promise<boolean> {
  const secret = Deno.env.get("RESEND_INBOUND_WEBHOOK_SECRET") || "";
  if (!secret) return false;
  const id = req.headers.get("svix-id");
  const ts = req.headers.get("svix-timestamp");
  const sigs = req.headers.get("svix-signature");
  if (!id || !ts || !sigs) return false;
  if (Math.abs(Date.now() / 1000 - Number(ts)) > 300) return false;
  const secretBytes = Uint8Array.from(
    atob(secret.startsWith("whsec_") ? secret.slice(6) : secret),
    (c) => c.charCodeAt(0),
  );
  const key = await crypto.subtle.importKey(
    "raw",
    secretBytes,
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const mac = await crypto.subtle.sign(
    "HMAC",
    key,
    enc.encode(`${id}.${ts}.${payload}`),
  );
  const expected = btoa(String.fromCharCode(...new Uint8Array(mac)));
  return sigs
    .split(" ")
    .some((s) => s.split(",")[1] === expected || s === `v1,${expected}`);
}

function extractAddress(from: string): string {
  const m = from.match(/<([^>]+)>/);
  return (m ? m[1] : from).trim().toLowerCase();
}

type FullEmail = {
  text: string;
  html: string;
  subject: string;
  spf: string;
  dkim: string;
  dmarc: string;
  autoGenerated: boolean;
};

async function fetchReceivedEmail(
  emailId: string,
  apiKey: string,
): Promise<FullEmail | null> {
  try {
    const res = await fetch(
      `https://api.resend.com/emails/receiving/${emailId}`,
      { headers: { Authorization: `Bearer ${apiKey}` } },
    );
    if (!res.ok) return null;
    const d = await res.json();
    const auth = d.authentication || {};
    const headerList: Array<{ name?: string; value?: string }> = Array.isArray(
      d.headers,
    )
      ? d.headers
      : [];
    const header = (n: string) =>
      String(
        headerList.find((h) => (h.name || "").toLowerCase() === n)?.value || "",
      ).toLowerCase();
    const autoGenerated =
      (header("auto-submitted") !== "" && header("auto-submitted") !== "no") ||
      /bulk|auto_reply|junk/.test(header("precedence")) ||
      header("x-auto-response-suppress").length > 0;
    return {
      text: d.text || "",
      html: d.html || "",
      subject: d.subject || "",
      spf: String(auth.spf || "none"),
      dkim: String(auth.dkim || "none"),
      dmarc: String(auth.dmarc || "none"),
      autoGenerated,
    };
  } catch {
    return null;
  }
}

function stripHtml(html: string): string {
  return html
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

type UploadFile = { media_type: string; data: string };

async function parseBooking(
  anthropicKey: string,
  subject: string,
  bodyText: string,
  file?: UploadFile | null,
): Promise<{ parsed: any; usage: any } | null> {
  const prompt = `This is a travel confirmation (forwarded email, screenshot, or ticket PDF). Extract booking facts as MINIFIED JSON only (no prose):
{"kind":"hotel"|"flight"|"train"|"other","status":"confirmed"|"cancelled","hotel":{"name":"","city":"","confirmation":"","checkin":"YYYY-MM-DD or empty","checkout":"YYYY-MM-DD or empty"},"flight":{"carrier":"","number":"","date":"YYYY-MM-DD or empty","depart_time":"HH:MM or empty","arrive_time":"","from":"","to":"","confirmation":""},"train":{"operator":"","name":"","number":"","date":"YYYY-MM-DD or empty","depart_time":"","arrive_time":"","from":"","to":"","class":"","confirmation":""},"summary":"one line describing the booking"}
Rules:
- Only facts explicitly present; empty strings for anything absent. NEVER invent times, dates or codes.
- kind="train" for ANY rail booking worldwide (Amtrak, Eurostar, DB, SNCF, Trenitalia, JR, IRCTC, ...). Keep operator, train name/number, stations and class VERBATIM as printed — do not translate or normalize.
- Flight from/to: "City (CODE)" when the city name appears anywhere (e.g. "London (LHR)"); bare code only if no city name is present. Train from/to: full station names as printed.
- Vendor hints: IRCTC PNR is 10 digits and trains print as "NUMBER NAME"; Eurostar/Amtrak refs are 6-char alphanumeric.
- Times 24h HH:MM.
- status="cancelled" for cancellation/refund/TDR notices — NEVER "confirmed" on those, even if they restate the original booking details.
- kind="other" if not clearly a hotel, flight or train booking.

SUBJECT: ${subject}
BODY:
${bodyText || (file ? "(see attached file)" : "(body unavailable — use the subject line only)")}`;
  const content: any[] = [];
  if (file)
    content.push(
      file.media_type === "application/pdf"
        ? {
            type: "document",
            source: {
              type: "base64",
              media_type: "application/pdf",
              data: file.data,
            },
          }
        : {
            type: "image",
            source: {
              type: "base64",
              media_type: file.media_type,
              data: file.data,
            },
          },
    );
  content.push({ type: "text", text: prompt });
  const aiRes = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "x-api-key": anthropicKey,
      "anthropic-version": "2023-06-01",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 500,
      messages: [{ role: "user", content }],
    }),
  });
  if (!aiRes.ok) return null;
  const ai = await aiRes.json();
  const rawOut = ai?.content?.[0]?.text || "{}";
  let parsed: any = {};
  try {
    parsed = JSON.parse(
      rawOut.slice(rawOut.indexOf("{"), rawOut.lastIndexOf("}") + 1),
    );
  } catch {
    parsed = { kind: "other", summary: subject };
  }
  return { parsed, usage: ai?.usage || {} };
}

// ── Travel legs ─────────────────────────────────────────────────────────
// Normalized leg the apply branch writes and dry_run previews. Returns
// null when the parse has neither an identity (number) nor a ref.
function normalizeLeg(parsed: any): any | null {
  const kind = parsed?.kind;
  if (kind !== "flight" && kind !== "train") return null;
  const src = kind === "flight" ? parsed.flight : parsed.train;
  if (!src) return null;
  const number = String(src.number || "").trim();
  const confirmation = String(src.confirmation || "").trim();
  if (!number && !confirmation) return null;
  // Trains display best as "Frecciarossa 9528" / "12951 Mumbai Rajdhani":
  // prefer the printed name as the carrier label when present.
  let carrier = String(
    (kind === "train" ? src.name || src.operator : src.carrier) || "",
  ).trim();
  // Models sometimes fold the number into the name ("Frecciarossa 9528",
  // IRCTC's "12951 MUMBAI RAJDHANI") — strip it from either end so
  // "carrier + number" displays don't double it.
  if (number) {
    const nl = number.toLowerCase();
    const cl = carrier.toLowerCase();
    if (cl.endsWith(nl))
      carrier = carrier.slice(0, carrier.length - number.length).trim();
    else if (cl.startsWith(nl)) carrier = carrier.slice(number.length).trim();
  }
  return {
    id: crypto.randomUUID(),
    kind,
    carrier,
    number,
    date: String(src.date || "").trim(),
    // Times must be clean 24h HH:MM — model output like "08:40 AM" or
    // "14:05+1" would otherwise poison the arrival_time timestamp compose
    // and 400 the whole leg save. Invalid → dropped, leg still saves.
    depart_time: validHHMM(src.depart_time)
      ? String(src.depart_time).trim()
      : "",
    arrive_time: validHHMM(src.arrive_time)
      ? String(src.arrive_time).trim()
      : "",
    from: String(src.from || "").trim(),
    to: String(src.to || "").trim(),
    confirmation,
    class: String(src.class || "").trim(),
    status: parsed.status === "cancelled" ? "cancelled" : "booked",
    via: "email",
    created_at: new Date().toISOString(),
  };
}

// Same leg? A shared ref is necessary but not sufficient — airlines issue
// ONE PNR for outbound + return, so a ref match must also agree on the
// number (when both are known) or it would merge the return into the
// outbound. Fallback identity: (kind, number, date).
function legMatches(a: any, b: any): boolean {
  const ac = String(a.confirmation || "");
  const bc = String(b.confirmation || "");
  const an = String(a.number || "");
  const bn = String(b.number || "");
  if (ac && bc && ac.toLowerCase() === bc.toLowerCase()) {
    if (!an || !bn || an.toLowerCase() === bn.toLowerCase()) return true;
  }
  return (
    a.kind === b.kind &&
    !!an &&
    an.toLowerCase() === bn.toLowerCase() &&
    a.date === b.date
  );
}

const validHHMM = (s: unknown): boolean =>
  /^([01]?\d|2[0-3]):[0-5]\d$/.test(String(s || ""));

const iataOf = (s: string): string => {
  const m = String(s || "").match(/\(([A-Z]{3})\)/);
  if (m) return m[1];
  const bare = String(s || "").trim();
  return /^[A-Z]{3}$/.test(bare) ? bare : "";
};
const cityOf = (s: string): string =>
  String(s || "")
    .replace(/\s*\([A-Z]{3}\)\s*/g, " ")
    .trim();

// Boundary auto-fill: a booked leg on the trip's first/last day fills the
// arrival/departure editors — only with genuinely parsed, validated times.
// An already-set time is overwritten ONLY for a reschedule of the same
// booking (isUpdate, ref-matched) whose airport agrees — never by a
// different flight to the same airport (e.g. a co-traveller's own leg on a
// shared trip). Returns the trips PATCH fields (or null).
function boundaryFill(
  trip: any,
  leg: any,
  isUpdate: boolean,
): Record<string, unknown> | null {
  if (leg.status !== "booked") return null;
  const mode = leg.kind === "flight" ? "flight" : "train";
  if (leg.date === trip.start_date && validHHMM(leg.arrive_time)) {
    const iata = leg.kind === "flight" ? iataOf(leg.to) : "";
    if (
      trip.arrival_time &&
      !(isUpdate && iata && iata === trip.arrival_airport_iata)
    )
      return null;
    const patch: Record<string, unknown> = {
      arrival_time: `${trip.start_date}T${leg.arrive_time}:00`,
      arrival_mode: mode,
    };
    if (iata) patch.arrival_airport_iata = iata;
    if (!trip.arrival_city) patch.arrival_city = cityOf(leg.to) || null;
    return patch;
  }
  if (leg.date === trip.end_date && validHHMM(leg.depart_time)) {
    const iata = leg.kind === "flight" ? iataOf(leg.from) : "";
    if (
      trip.departure_time &&
      !(isUpdate && iata && iata === trip.departure_airport_iata)
    )
      return null;
    const patch: Record<string, unknown> = {
      departure_time: `${trip.end_date}T${leg.depart_time}:00`,
      departure_mode: mode,
    };
    if (iata) patch.departure_airport_iata = iata;
    if (!trip.departure_city) patch.departure_city = cityOf(leg.from) || null;
    return patch;
  }
  return null;
}

// Member-aware candidates: trips the user created OR is a member of, not
// yet ended — so co-travellers' forwards can route to shared trips.
async function fetchCandidates(
  supabaseUrl: string,
  db: Record<string, string>,
  userId: string,
): Promise<any[]> {
  const today = new Date().toISOString().slice(0, 10);
  let memberIds: string[] = [];
  try {
    const mRes = await fetch(
      `${supabaseUrl}/rest/v1/trip_members?user_id=eq.${userId}&select=trip_id`,
      { headers: db },
    );
    if (mRes.ok) memberIds = (await mRes.json()).map((r: any) => r.trip_id);
  } catch {
    /* member lookup best-effort */
  }
  const orParts = [`created_by.eq.${userId}`];
  if (memberIds.length)
    orParts.push(`id.in.(${memberIds.slice(0, 50).join(",")})`);
  const tRes = await fetch(
    `${supabaseUrl}/rest/v1/trips?or=(${orParts.join(",")})&end_date=gte.${today}&select=id,name,hotels_data,travel_data,destination,start_date,end_date,arrival_city,arrival_time,arrival_airport_iata,departure_city,departure_time,departure_airport_iata&order=start_date.asc&limit=100`,
    { headers: db },
  );
  return tRes.ok ? await tRes.json() : [];
}

// plus_miss: an explicit trip address that matches nothing must STOP the
// pipeline (receipt + no writes), never fall through to a guess.
function routeTrip(
  candidates: any[],
  parsed: any,
  toAddrs: string[],
): { trip: any; routedBy: string } {
  const plusMatch = toAddrs
    .map((a) => a.match(/\+([a-f0-9-]{4,36})@/))
    .find(Boolean);
  if (plusMatch) {
    const code = plusMatch[1];
    const trip = candidates.find((t) => String(t.id).startsWith(code)) || null;
    return trip
      ? { trip, routedBy: "trip_address" }
      : { trip: null, routedBy: "plus_miss" };
  }
  if (parsed.kind === "hotel" && parsed.hotel?.checkin) {
    const ci = parsed.hotel.checkin;
    const trip =
      candidates.find((t) => ci >= t.start_date && ci <= t.end_date) || null;
    if (trip) return { trip, routedBy: "checkin_date" };
  }
  const legDate = parsed.flight?.date || parsed.train?.date;
  if ((parsed.kind === "flight" || parsed.kind === "train") && legDate) {
    const trip =
      candidates.find(
        (t) => legDate >= t.start_date && legDate <= t.end_date,
      ) || null;
    if (trip) return { trip, routedBy: "leg_date" };
  }
  return { trip: candidates[0] || null, routedBy: "fallback" };
}

/* P0 — reply-back receipt. Callers must esc() every email-derived value in
 * heading/line. Loop-safety: Auto-Submitted, threaded, verified senders
 * only, 20/day cap (log insert AWAITED so the counter is reliable). */
async function sendReceipt(opts: {
  supabaseUrl: string;
  db: Record<string, string>;
  to: string;
  origSubject: string;
  origMessageId: string;
  heading: string;
  line: string;
  tripId?: string;
  senderProfileId?: string;
}): Promise<void> {
  try {
    const key = Deno.env.get("RESEND_API_KEY");
    const from = Deno.env.get("EMAIL_FROM") || "TripJam <trips@tripjam.co>";
    if (!key) return;
    const dayAgo = new Date(Date.now() - 24 * 3600 * 1000).toISOString();
    const capRes = await fetch(
      `${opts.supabaseUrl}/rest/v1/email_log?type=eq.receipt&recipient=eq.${encodeURIComponent(opts.to)}&created_at=gte.${dayAgo}&select=id`,
      { headers: opts.db },
    );
    if (capRes.ok && (await capRes.json()).length >= 20) return;
    const tripUrl = opts.tripId
      ? `https://tripjam.co/trip/${opts.tripId}`
      : "https://tripjam.co";
    const html = `
  <div style="max-width:480px;margin:0 auto;background:#fff;border:1px solid #E2DDD5;border-radius:16px;padding:28px;font-family:Georgia,serif">
    <div style="font-size:14px;letter-spacing:.08em;color:#587284;margin-bottom:14px">TRIPJAM</div>
    <div style="font-size:20px;margin-bottom:10px">${opts.heading}</div>
    <div style="font-size:14px;line-height:1.6;color:#3a4a58;margin-bottom:22px">${opts.line}</div>
    <a href="${tripUrl}" style="display:inline-block;background:#2563A8;color:#fff;text-decoration:none;border-radius:10px;padding:11px 22px;font-size:14px">Open the trip</a>
  </div>`;
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${key}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from,
        to: [opts.to],
        subject:
          `Re: ${stripCrlf(opts.origSubject) || "your forwarded booking"}`.slice(
            0,
            160,
          ),
        html,
        headers: {
          "Auto-Submitted": "auto-replied",
          ...(opts.origMessageId
            ? {
                "In-Reply-To": opts.origMessageId,
                References: opts.origMessageId,
              }
            : {}),
        },
      }),
    });
    if (res.ok)
      // Awaited: this row IS the rate-limit counter — a dropped write
      // would make the cap soft.
      await fetch(`${opts.supabaseUrl}/rest/v1/email_log`, {
        method: "POST",
        headers: opts.db,
        body: JSON.stringify({
          type: "receipt",
          recipient: opts.to,
          sender_id: opts.senderProfileId || null,
          trip_id: opts.tripId || null,
        }),
      });
  } catch {
    /* receipts are best-effort */
  }
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS")
    return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST")
    return new Response("method not allowed", {
      status: 405,
      headers: corsHeaders,
    });

  const payload = await req.text();

  // Dry-run mode: authenticated parse+route diagnostics, no trip writes.
  // Metered: llm_usage row + 30 runs/user/day.
  try {
    const maybe = JSON.parse(payload);
    if (maybe?.dry_run === true) {
      const auth = req.headers.get("authorization") || "";
      const userRes = await fetch(
        `${Deno.env.get("SUPABASE_URL")}/auth/v1/user`,
        {
          headers: {
            Authorization: auth,
            apikey: Deno.env.get("SUPABASE_ANON_KEY") || "",
          },
        },
      );
      if (!userRes.ok)
        return new Response(JSON.stringify({ error: "unauthorized" }), {
          status: 401,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      const user = await userRes.json();
      const sk = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
      const sUrl = Deno.env.get("SUPABASE_URL")!;
      const dbh = {
        apikey: sk,
        Authorization: `Bearer ${sk}`,
        "Content-Type": "application/json",
      };
      const dayAgo = new Date(Date.now() - 24 * 3600 * 1000).toISOString();
      const capRes = await fetch(
        `${sUrl}/rest/v1/llm_usage?function_name=eq.inbound-email:dry&user_id=eq.${user.id}&created_at=gte.${dayAgo}&select=id`,
        { headers: dbh },
      ).catch(() => null);
      if (capRes?.ok && (await capRes.json()).length >= 30)
        return new Response(JSON.stringify({ error: "daily dry-run cap" }), {
          status: 429,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      // Optional upload: screenshot or ticket PDF, base64. 4MB binary ≈
      // 5.6M base64 chars; reject oversize/unknown types before Anthropic.
      let file: UploadFile | null = null;
      if (maybe.file) {
        const mt = String(maybe.file.media_type || "");
        const okTypes = [
          "image/jpeg",
          "image/png",
          "image/webp",
          "application/pdf",
        ];
        const data = String(maybe.file.data || "");
        if (!okTypes.includes(mt) || !data)
          return new Response(
            JSON.stringify({ error: "unsupported file type" }),
            {
              status: 415,
              headers: { ...corsHeaders, "Content-Type": "application/json" },
            },
          );
        if (data.length > 5_600_000)
          return new Response(JSON.stringify({ error: "file too large" }), {
            status: 413,
            headers: { ...corsHeaders, "Content-Type": "application/json" },
          });
        // PDFs: page-count cap (a 4MB PDF can be hundreds of Haiku-vision
        // pages; the client caps at 3.5MB but a raw JWT caller isn't bound
        // by the client). Malformed base64 → Anthropic rejects downstream.
        if (mt === "application/pdf") {
          try {
            const head = atob(data);
            const pages = (head.match(/\/Type\s*\/Page[^s]/g) || []).length;
            if (pages > 8)
              return new Response(
                JSON.stringify({ error: "PDF too long (max 8 pages)" }),
                {
                  status: 413,
                  headers: {
                    ...corsHeaders,
                    "Content-Type": "application/json",
                  },
                },
              );
          } catch {
            return new Response(JSON.stringify({ error: "bad file data" }), {
              status: 400,
              headers: { ...corsHeaders, "Content-Type": "application/json" },
            });
          }
        }
        file = { media_type: mt, data };
      }
      const cands = await fetchCandidates(sUrl, dbh, user.id);
      const pr = await parseBooking(
        Deno.env.get("ANTHROPIC_API_KEY")!,
        String(maybe.subject || ""),
        String(maybe.body || "").slice(0, 8000),
        file,
      );
      if (!pr)
        return new Response(JSON.stringify({ error: "parse failed" }), {
          status: 502,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      // Awaited: these rows ARE the 30/day meter — a dropped write would
      // make the cap soft (same reasoning as the receipt counter).
      await fetch(`${sUrl}/rest/v1/llm_usage`, {
        method: "POST",
        headers: dbh,
        body: JSON.stringify({
          function_name: "inbound-email:dry",
          model: "claude-haiku-4-5-20251001",
          user_id: user.id,
          input_tokens: pr.usage?.input_tokens || 0,
          output_tokens: pr.usage?.output_tokens || 0,
        }),
      }).catch(() => {});
      const routed = cands.length
        ? routeTrip(
            cands,
            pr.parsed,
            (maybe.to ? [String(maybe.to)] : []).map((s) => s.toLowerCase()),
          )
        : { trip: null, routedBy: "no_active_trip" };
      return Response.json(
        {
          dry_run: true,
          parsed: pr.parsed,
          leg_preview: normalizeLeg(pr.parsed),
          routedBy: routed.routedBy,
          trip: routed.trip?.name || null,
          candidates: cands.map((c) => c.name),
        },
        { headers: corsHeaders },
      );
    }
  } catch {
    /* not JSON or not dry_run — fall through to webhook path */
  }

  if (!(await verifySvix(req, payload)))
    return new Response(JSON.stringify({ error: "invalid signature" }), {
      status: 401,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  let event: any;
  try {
    event = JSON.parse(payload);
  } catch {
    return new Response("bad payload", { status: 400, headers: corsHeaders });
  }
  if (event.type !== "email.received")
    return Response.json({ ignored: event.type }, { headers: corsHeaders });

  const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const anthropicKey = Deno.env.get("ANTHROPIC_API_KEY")!;
  const resendKey =
    Deno.env.get("RESEND_INBOUND_API_KEY") || Deno.env.get("RESEND_API_KEY")!;
  const db = {
    apikey: serviceKey,
    Authorization: `Bearer ${serviceKey}`,
    "Content-Type": "application/json",
  };

  const data = event.data || {};
  const sender = extractAddress(String(data.from || ""));
  const messageId = String(data.message_id || data.email_id || "");
  const subject = String(data.subject || "");

  // No message identity → no dedupe possible → drop (a constant key would
  // make the first such email swallow all later ones).
  if (!messageId)
    return Response.json(
      { dropped: "no message id" },
      { headers: corsHeaders },
    );

  // ── Claim-first dedupe: INSERT the marker BEFORE processing. The partial
  // unique index on email_log(type) for 'inbound:%' makes retries collide
  // here instead of double-processing (receipts, feed rows, bookings).
  const dedupeKey = `inbound:${messageId}`.slice(0, 250);
  const claim = await fetch(`${supabaseUrl}/rest/v1/email_log`, {
    method: "POST",
    headers: db,
    body: JSON.stringify({ type: dedupeKey, recipient: sender }),
  });
  if (!claim.ok) {
    const errText = await claim.text();
    if (/duplicate|23505|unique/i.test(errText))
      return Response.json({ deduped: true }, { headers: corsHeaders });
    return new Response(JSON.stringify({ error: "claim failed" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  // ── Sender → user (silent drop for unknowns — no probing oracle) ──────
  const profRes = await fetch(
    `${supabaseUrl}/rest/v1/profiles?email=eq.${encodeURIComponent(sender)}&select=id&limit=1`,
    { headers: db },
  );
  const prof = profRes.ok ? (await profRes.json())[0] : null;
  if (!prof)
    return Response.json(
      { dropped: "unknown sender" },
      { headers: corsHeaders },
    );

  // ── Per-sender processing cap (the claim rows are the meter) ─────────
  const dayAgo = new Date(Date.now() - 24 * 3600 * 1000).toISOString();
  const meterRes = await fetch(
    `${supabaseUrl}/rest/v1/email_log?type=like.inbound:*&recipient=eq.${encodeURIComponent(sender)}&created_at=gte.${dayAgo}&select=id`,
    { headers: db },
  );
  if (meterRes.ok && (await meterRes.json()).length > 20)
    return Response.json({ dropped: "daily cap" }, { headers: corsHeaders });

  // ── Full content + SENDER authenticity (fail-closed) ─────────────────
  const full = await fetchReceivedEmail(String(data.email_id || ""), resendKey);
  if (!full)
    return Response.json(
      { dropped: "content unavailable — cannot verify sender" },
      { headers: corsHeaders },
    );
  if ((full.spf !== "pass" && full.dkim !== "pass") || full.dmarc === "fail")
    return Response.json(
      { dropped: "sender authentication failed" },
      { headers: corsHeaders },
    );
  if (full.autoGenerated)
    return Response.json(
      { dropped: "auto-generated mail" },
      { headers: corsHeaders },
    );
  const bodyText = (full.text || stripHtml(full.html)).slice(0, 8000);

  // ── Candidates (member-aware) ─────────────────────────────────────────
  const candidates = await fetchCandidates(supabaseUrl, db, prof.id);
  if (candidates.length === 0) {
    await sendReceipt({
      supabaseUrl,
      db,
      to: sender,
      origSubject: subject,
      origMessageId: messageId,
      heading: "No upcoming trip to attach this to",
      line: "We received your booking email, but there's no upcoming trip on your account yet. Create the trip first, then forward it again.",
      senderProfileId: prof.id,
    });
    return Response.json(
      { dropped: "no active trip" },
      { headers: corsHeaders },
    );
  }

  // ── Parse ─────────────────────────────────────────────────────────────
  const pr = await parseBooking(anthropicKey, subject, bodyText);
  if (!pr)
    return new Response(JSON.stringify({ error: "parse model failed" }), {
      status: 502,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  const parsed = pr.parsed;

  // ── Route ─────────────────────────────────────────────────────────────
  const toAddrs: string[] = Array.isArray(data.to)
    ? data.to.map((t: any) => String(t).toLowerCase())
    : [String(data.to || "").toLowerCase()];
  const { trip, routedBy } = routeTrip(candidates, parsed, toAddrs);

  if (routedBy === "plus_miss" || !trip) {
    await sendReceipt({
      supabaseUrl,
      db,
      to: sender,
      origSubject: subject,
      origMessageId: messageId,
      heading: "That trip address didn't match",
      line: "The trip this address points to has ended or isn't on your account. Grab the current address from the trip's Travel & Hotels section and forward again.",
      senderProfileId: prof.id,
    });
    return Response.json(
      { dropped: "plus address matched no trip" },
      { headers: corsHeaders },
    );
  }

  // usage log (fire-and-forget)
  fetch(`${supabaseUrl}/rest/v1/llm_usage`, {
    method: "POST",
    headers: db,
    body: JSON.stringify({
      trip_id: trip.id,
      function_name: "inbound-email",
      model: "claude-haiku-4-5-20251001",
      input_tokens: pr.usage?.input_tokens || 0,
      output_tokens: pr.usage?.output_tokens || 0,
    }),
  }).catch(() => {});

  // ── Apply ─────────────────────────────────────────────────────────────
  let applied = "logged";
  let appliedLeg: any = null;
  let boundarySide: "arrival" | "departure" | "" = "";
  if (
    parsed.kind === "hotel" &&
    parsed.hotel?.name &&
    parsed.status === "cancelled"
  ) {
    const list: any[] = Array.isArray(trip.hotels_data)
      ? [...trip.hotels_data]
      : [];
    const idx = list.findIndex(
      (x) =>
        x.name?.toLowerCase() === parsed.hotel.name.toLowerCase() ||
        (parsed.hotel.confirmation &&
          x.confirmation === parsed.hotel.confirmation),
    );
    if (idx >= 0) {
      list[idx] = { ...list[idx], status: null, confirmation: "" };
      const upd = await fetch(`${supabaseUrl}/rest/v1/trips?id=eq.${trip.id}`, {
        method: "PATCH",
        headers: { ...db, Prefer: "return=representation" },
        body: JSON.stringify({ hotels_data: list }),
      });
      applied = upd.ok ? "hotel_unbooked" : "hotel_update_failed";
    } else {
      applied = "cancellation_noted";
    }
  } else if (parsed.kind === "hotel" && parsed.hotel?.name) {
    const h = parsed.hotel;
    const list: any[] = Array.isArray(trip.hotels_data)
      ? [...trip.hotels_data]
      : [];
    // Match by identity (name/confirmation) first; a same-city slot only
    // absorbs the booking when it isn't already a DIFFERENT booked hotel —
    // never silently destroy an existing booking's confirmation.
    let idx = list.findIndex(
      (x) =>
        x.name?.toLowerCase() === h.name.toLowerCase() ||
        (h.confirmation && x.confirmation === h.confirmation),
    );
    if (idx < 0)
      idx = list.findIndex(
        (x) =>
          h.city &&
          x.city?.toLowerCase() === h.city.toLowerCase() &&
          x.status !== "booked",
      );
    const entry = {
      city: idx >= 0 ? list[idx].city : h.city || trip.destination,
      name: h.name,
      status: "booked",
      confirmation: h.confirmation || "",
      via: "email",
    };
    if (idx >= 0) list[idx] = { ...list[idx], ...entry };
    else list.push(entry);
    const upd = await fetch(`${supabaseUrl}/rest/v1/trips?id=eq.${trip.id}`, {
      method: "PATCH",
      headers: { ...db, Prefer: "return=representation" },
      body: JSON.stringify({ hotels_data: list }),
    });
    applied = upd.ok ? "hotel_booked" : "hotel_update_failed";
  } else if (parsed.kind === "flight" || parsed.kind === "train") {
    // ── Travel legs: any count, any date. Mid-trip legs are first-class;
    // the frontend surfaces them on their itinerary day. Tickets dated
    // outside the trip range still store (the ticket is ground truth).
    const leg = normalizeLeg(parsed);
    if (leg) {
      const list: any[] = Array.isArray(trip.travel_data)
        ? [...trip.travel_data]
        : [];
      const idx = list.findIndex((x) => legMatches(x, leg));
      if (parsed.status === "cancelled") {
        if (idx >= 0) {
          list[idx] = { ...list[idx], status: "cancelled" };
          const upd = await fetch(
            `${supabaseUrl}/rest/v1/trips?id=eq.${trip.id}`,
            {
              method: "PATCH",
              headers: { ...db, Prefer: "return=representation" },
              body: JSON.stringify({ travel_data: list }),
            },
          );
          applied = upd.ok ? "leg_cancelled" : "leg_update_failed";
        } else {
          applied = "leg_cancellation_noted";
        }
      } else {
        if (idx >= 0) {
          // Reschedule/re-forward: merge, non-empty new values win.
          const merged = { ...list[idx] };
          for (const k of [
            "carrier",
            "number",
            "date",
            "depart_time",
            "arrive_time",
            "from",
            "to",
            "confirmation",
            "class",
          ])
            if (leg[k]) merged[k] = leg[k];
          merged.status = "booked";
          list[idx] = merged;
          appliedLeg = merged;
          applied = "leg_updated";
        } else {
          list.push(leg);
          appliedLeg = leg;
          applied = "leg_booked";
        }
        const fill = boundaryFill(trip, appliedLeg, idx >= 0);
        const upd = await fetch(
          `${supabaseUrl}/rest/v1/trips?id=eq.${trip.id}`,
          {
            method: "PATCH",
            headers: { ...db, Prefer: "return=representation" },
            body: JSON.stringify({ travel_data: list, ...(fill || {}) }),
          },
        );
        if (!upd.ok) applied = "leg_update_failed";
        else if (fill)
          boundarySide = fill.arrival_time ? "arrival" : "departure";
      }
    }
  }

  // feed row
  await fetch(`${supabaseUrl}/rest/v1/activity_log`, {
    method: "POST",
    headers: db,
    body: JSON.stringify({
      trip_id: trip.id,
      user_id: prof.id,
      action: "email_ingested",
      entity_type: "trip",
      entity_id: trip.id,
      summary:
        (parsed.summary ||
          `forwarded a booking email${parsed.hotel?.name ? ` — ${parsed.hotel.name}` : ""}`) +
        (appliedLeg?.date &&
        (appliedLeg.date < trip.start_date || appliedLeg.date > trip.end_date)
          ? " (dates outside trip)"
          : "") +
        (routedBy !== "fallback" ? "" : " (routed to soonest trip)"),
    }),
  }).catch(() => {});

  // ── P0: outcome receipt (all email-derived values escaped) ────────────
  const receipt = (() => {
    const tripLabel = `<b>${esc(trip.name)}</b>`;
    if (applied === "hotel_booked")
      return {
        heading: `✓ ${esc(parsed.hotel.name)} is booked`,
        line: `Marked as booked on ${tripLabel}${parsed.hotel.confirmation ? ` with confirmation <b>#${esc(parsed.hotel.confirmation)}</b>` : ""}. You'll see it on the itinerary and in Travel &amp; Hotels.`,
      };
    if (applied === "hotel_unbooked")
      return {
        heading: `Cancellation noted — ${esc(parsed.hotel.name)}`,
        line: `That stay is no longer marked booked on ${tripLabel}.`,
      };
    if (applied === "cancellation_noted")
      return {
        heading: "Cancellation received",
        line: `We noted the cancellation on ${tripLabel}'s activity feed — no matching booked stay to update.`,
      };
    if (applied === "hotel_update_failed" || applied === "leg_update_failed")
      return {
        heading: "We hit a snag saving that booking",
        line: `We read the booking fine but couldn't save it to ${tripLabel} just now. Forward it once more in a few minutes.`,
      };
    if (applied === "leg_booked" || applied === "leg_updated") {
      const l = appliedLeg;
      const icon = l.kind === "flight" ? "✈️" : "🚆";
      const label =
        [l.carrier, l.number].filter(Boolean).join(" ") ||
        (l.kind === "flight" ? "Your flight" : "Your train");
      // Day N mention for mid-trip legs (boundary legs get the auto-fill
      // sentence instead).
      let daySuffix = "";
      if (boundarySide) {
        daySuffix = `, and your ${boundarySide} day now shows it`;
      } else if (
        l.date &&
        l.date >= trip.start_date &&
        l.date <= trip.end_date
      ) {
        const dayN =
          Math.round(
            (Date.parse(l.date) - Date.parse(trip.start_date)) / 86400000,
          ) + 1;
        daySuffix = ` — you'll see it on Day ${dayN}`;
      }
      return {
        heading: `${icon} ${esc(label)} is on your trip`,
        line: `<b>${esc(l.from)} → ${esc(l.to)}</b>${l.date ? ` on ${esc(l.date)}` : ""}${l.depart_time ? `, departing ${esc(l.depart_time)}` : ""}${l.confirmation ? `, ref <b>${esc(l.confirmation)}</b>` : ""} — ${applied === "leg_updated" ? "updated on" : "saved to"} ${tripLabel}'s Travel &amp; Hotels${daySuffix}.`,
      };
    }
    if (applied === "leg_cancelled") {
      const l = parsed.kind === "flight" ? parsed.flight : parsed.train;
      return {
        heading: `Cancellation noted — ${esc([l?.carrier || l?.name || l?.operator, l?.number].filter(Boolean).join(" "))}`,
        line: `That ${parsed.kind} is marked cancelled on ${tripLabel}.`,
      };
    }
    if (applied === "leg_cancellation_noted")
      return {
        heading: "Cancellation received",
        line: `We noted it on ${tripLabel}'s activity feed — no matching booked ${esc(parsed.kind)} to update.`,
      };
    return {
      heading: "We couldn't read that as a booking",
      line: `It's saved on ${tripLabel}'s activity feed, but nothing was booked. Forwarding the original confirmation email (rather than a summary) usually works best.`,
    };
  })();
  await sendReceipt({
    supabaseUrl,
    db,
    to: sender,
    origSubject: subject,
    origMessageId: messageId,
    heading: receipt.heading,
    line: receipt.line,
    tripId: trip.id,
    senderProfileId: prof.id,
  });

  return Response.json(
    { ok: true, applied, kind: parsed.kind, trip: trip.name, routedBy },
    { headers: corsHeaders },
  );
});
